version: '2'

services:
 rproxy:
    image: nginx:1.16-alpine
    ports: 
        - "80:80"
    volumes:
        - ./rproxy:/etc/nginx/conf.d/
    depends_on: 
        - web 

 web:
    image: nginx:1.16-alpine
    volumes:
        - ./code:/code
        - ./nginx:/etc/nginx/conf.d/
    links:
        - php

 php:
    image: php:7-fpm
    volumes:
        - ./code:/code
